### ISSUE TITLE
found for loop has 14 operations and map method has 9 operations

### ISSUE THREAD

**Issue by js08** [andyttran/guide_to_algorithms#1]
hello,

- i am trying to understand the complexity of map method in js.
- can you tell me which one is better one.
- since in some of my react code I see people using map method http://jsfiddle.net/jhudson8/135oo6f8/.
- not sure when to use map method and for loop.
- I am providing two codes below.
- using this example I calculated complexity https://github.com/andyttran/guide_to_algorithms#1c-analyze-line-by-line
- and found for loop has 14 operations and map method has 9 operations.
- in the coments below I have given value one for e ch operation.
- can you tell me whether I have done it correctly

for loop

var cars =[
			{'toyota' : 'corolla', 'honda' : 'civic'},
			{'toyota' : 'corolla1', 'honda' : 'civic1'},
			{'toyota' : 'corolla2', 'honda' : 'civic2'},
			{'toyota' : 'corolla3', 'honda' : 'civic3'},
	];
var names = []; //names = 1, [] = 1
for(var i=0; i< cars.length; i++) {  //  for = 1 , var i = 1, =0 = 1, < = 1, cars.length = 1, i++ = 1
	names.push(cars[i].toyota); //names = 1, push = 1, cars[i] = 1, toyota = 1
}
console.log(names); has an array access and then a printing to the console, so thats 2 operations
total = 14

map method js

var cars =[
			{'toyota' : 'corolla', 'honda' : 'civic'},
			{'toyota' : 'corolla1', 'honda' : 'civic1'},
			{'toyota' : 'corolla2', 'honda' : 'civic2'},
			{'toyota' : 'corolla3', 'honda' : 'civic3'},
	];

var mapValues = cars.map(function(animal){ //mapvalues = 1, cars = 1, map= 1, function= 1
	return animal.toyota; //return = 1, animal = 1, toyota = 1
});
console.log(mapValues); // has an array access and then a printing to the console, so thats 2 operations
total = 9

**Comment by andyttran** [comment]
The map internally will perform a for loop, therefore if you run the map, you will get more than 1 operation.  

The big key to keep in mind is that, whether you perform a for loop or a map function, you will still end up with O(N).  This is because as there are more items in the cars array, there will be more iterations.
